name: Build Flet GUI Application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flet[desktop] pandas openpyxl pyinstaller==6.3.0

    - name: Build EXE with PyInstaller
      run: |
        # Вшиваем site.html внутрь исполняемого файла
        pyinstaller --noconsole --onefile --collect-all flet --collect-all flet_desktop --add-data "site.html;." --name "ZPay_Games_Store" main.py

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ZPay_Games_Store_Windows
        path: dist/ZPay_Games_Store.exe
